pipeline:
  - name: setup
    type: command
    command: $WORKING_DIR/setup.sh
    only_if: test "$WERCKER" = "true"
  - name: Make $HOME/.ssh directory
    type: command
    command: mkdir -p $HOME/.ssh
    only_if: test "$WERCKER" = "true"
  - name: Put SSH publick key
    type: command
    command: echo "$DIGITALOCEAN_SSH_KEY_PUBLIC" > $HOME/.ssh/id_rsa.pub
    only_if: test "$WERCKER" = "true"
  - name: Put SSH private key
    type: command
    command: echo $DIGITALOCEAN_SSH_KEY_PRIVATE > $HOME/.ssh/id_rsa
    only_if: test "$WERCKER" = "true"
  - name: chmod 600 $HOME/.ssh/id_rsa
    type: command
    command: chmod 600 $HOME/.ssh/id_rsa
    only_if: test "$WERCKER" = "true"
  - name: Run vagrant up coreos
    type: command
    command: vagrant up coreos --provider=digital_ocean
    only_if: test "$WERCKER_GIT_REPOSITORY" != "serverspec"
  - name: Run apply-itamae-and-serverspec-to-docker.sh
    type: command
    command: ./apply-itamae-and-serverspec-to-docker.sh
    directory: $WORKING_DIR
    only_if: test "$WERCKER_GIT_REPOSITORY" != "serverspec"
  - name: Run vagrant up centos65
    type: command
    command: vagrant up centos65 --provider=digital_ocean
    directory: $WORKING_DIR
  - name: Run itamae
    type: command
    command: bundle exec itamae ssh --host centos65 --vagrant recipe.rb
    directory: $WORKING_DIR
  - name: Run vagrant reload centos65
    type: command
    command: vagrant reload centos65
    directory: $WORKING_DIR
  - name: Run rake spec:centos65
    type: command
    command: DIGITALOCEAN=true rake spec:centos65
    directory: $WORKING_DIR
  - name: Run vagrant up centos70
    type: command
    command: vagrant up centos70 --provider=digital_ocean
    directory: $WORKING_DIR
  - name: Run itamae
    type: command
    command: bundle exec itamae ssh --host centos70 --vagrant recipe.rb
    directory: $WORKING_DIR
  - name: Run vagrant reload centos70
    type: command
    command: vagrant reload centos70
    directory: $WORKING_DIR
  - name: Run rake spec:centos70
    type: command
    command: DIGITALOCEAN=true rake spec:centos70
    directory: $WORKING_DIR
  - name: Run vagrant up ubuntu1404
    type: command
    command: vagrant up ubuntu1404 --provider=digital_ocean
    directory: $WORKING_DIR
  - name: Run itamae
    type: command
    command: bundle exec itamae ssh --host ubuntu1404 --vagrant recipe.rb
    directory: $WORKING_DIR
  - name: Run vagrant reload ubuntu1404
    type: command
    command: vagrant reload ubuntu1404
    directory: $WORKING_DIR
  - name: Run rake spec:ubuntu1404
    type: command
    command: DIGITALOCEAN=true rake spec:ubuntu1404
    directory: $WORKING_DIR
cleanup:
  - name: vagrant destroy
    command: vagrant destroy --force
    directory: $WORKING_DIR
