require:
  - ./coreos.yml
  - ./centos65.yml
  - ./centos70.yml
  - ./ubuntu1404.yml
  - ./freebsd101.yml

pipeline:
  - name: setup
    type: command
    command: $WORKING_DIR/setup.sh
    only_if: test "$WERCKER" = "true"
  - name: Make $HOME/.ssh directory
    type: command
    command: mkdir -p $HOME/.ssh
    only_if: test "$WERCKER" = "true"
  - name: Put SSH publick key
    type: command
    command: echo "$DIGITALOCEAN_SSH_KEY_PUBLIC" > $HOME/.ssh/id_rsa.pub
    only_if: test "$WERCKER" = "true"
  - name: Put SSH private key
    type: command
    command: echo $DIGITALOCEAN_SSH_KEY_PRIVATE > $HOME/.ssh/id_rsa
    only_if: test "$WERCKER" = "true"
  - name: chmod 600 $HOME/.ssh/id_rsa
    type: command
    command: chmod 600 $HOME/.ssh/id_rsa
    only_if: test "$WERCKER" = "true"
  - name: Parallel builds each OSes
    parallel:
      - call: coreos::build
      - call: centos65::build
      - call: centos70::build
      - call: ubuntu1404::build
      - call: freebsd101::build
cleanup:
  - name: vagrant destroy
    command: vagrant destroy --force
    directory: $WORKING_DIR
messenger:
  type: slack
  channel: serverspec
  url: $SLACK_WEBHOOK_URL
  icon_url: https://raw.githubusercontent.com/serverspec/serverspec-integration-test/master/walter.png
  username: Walter
