pipeline:
  - name: Make $HOME/.ssh directory
    type: command
    command: mkdir -p $HOME/.ssh
    only_if: test "$WERCKER" = "true"
  - name: Put SSH publick key
    type: command
    command: echo "$DIGITALOCEAN_SSH_KEY_PUBLIC" > $HOME/.ssh/id_rsa.pub
    only_if: test "$WERCKER" = "true"
  - name: Put SSH private key
    type: command
    command: echo $DIGITALOCEAN_SSH_KEY_PRIVATE > $HOME/.ssh/id_rsa
    only_if: test "$WERCKER" = "true"
  - name: chmod 600 $HOME/.ssh/id_rsa
    type: command
    command: chmod 600 $HOME/.ssh/id_rsa
    only_if: test "$WERCKER" = "true"
  - name: Run vagrant up centos65
    type: command
    command: vagrant up centos65 --provider=digital_ocean
  - name: Run itamae
    type: command
    command: bundle exec itamae ssh --host centos65 --vagrant recipe.rb
  - name: Run vagrant reload centos65
    type: command
    command: vagrant reload centos65
  - name: Run rake spec:centos65
    type: command
    command: DIGITALOCEAN=true rake spec:centos65
  - name: Run vagrant up centos70
    type: command
    command: vagrant up centos70 --provider=digital_ocean
  - name: Run itamae
    type: command
    command: bundle exec itamae ssh --host centos70 --vagrant recipe.rb
  - name: Run vagrant reload centos70
    type: command
    command: vagrant reload centos70
  - name: Run rake spec:centos70
    type: command
    command: DIGITALOCEAN=true rake spec:centos70
  - name: Run vagrant up ubuntu1404
    type: command
    command: vagrant up ubuntu1404 --provider=digital_ocean
  - name: Run itamae
    type: command
    command: bundle exec itamae ssh --host ubuntu1404 --vagrant recipe.rb
  - name: Run vagrant reload ubuntu1404
    type: command
    command: vagrant reload ubuntu1404
  - name: Run rake spec:ubuntu1404
    type: command
    command: DIGITALOCEAN=true rake spec:ubuntu1404
