namespace: ubuntu1404

stages:
  - def:
      name: build
      type: command
      command: vagrant up ubuntu1404 --provider=digital_ocean && bundle exec itamae ssh --host ubuntu1404 --vagrant recipe.rb && DIGITALOCEAN=true rake spec:ubuntu1404
      directory: $WORKING_DIR
